### ISSUE TITLE
Make install does not build

### ISSUE THREAD

**Issue by hgn** [protocollabs/maparo#26]
```
go install mapago-client.go 
go install: no install location for .go files listed on command line (GOBIN not set)
```

Why does it call go install? Should call `go build` ...

Please: wrote a **full** example in the README.md how to install and build the package. Inculding how to setup GOPATH. New users (not aware of go) should copy and paste the shell commands and execute them. At the end the executable should be generated.

**Comment by monfron** [comment]
Fixed by: https://github.com/protocollabs/mapago/commit/b85c59c768b1559107b0ae4f526ded1e5302f616
