### ISSUE TITLE
Check & Stick with best QUIC Implementations

### ISSUE THREAD

**Issue by hgn** [protocollabs/maparo#4]
Check the available Quic Implementations. Answer questrions like:

- development activity? Under high dev or outdated?
- is the goal IETF QUIC compatibility or still focusing on Google Quic?
  - What about interop tests?
- if Quic Implementation is written in other language than Go: Implement wrapper!

https://github.com/lucas-clemente/quic-go

**Comment by monfron** [comment]
already done:
- play around with different implementations: 1. ngtcp, 2. picoquic, 3. quant, 4. quicgo
